import type { TripWorkspaceData } from "@/types/trip";

const now = new Date().toISOString();

export const demoWorkspace: TripWorkspaceData = {
  trip: {
    id: "demo-trip",
    owner_id: "demo-user",
    name: "Rinjani Long Weekend",
    destination: "Lombok, Nusa Tenggara Barat",
    trip_type: "hiking",
    start_date: "2026-07-10",
    end_date: "2026-07-14",
    target_budget: 4500000,
    currency: "IDR",
    description: "Pendakian singkat dengan pembagian biaya yang rapi.",
    invite_code: "RINJANI26",
    created_at: now,
    updated_at: now,
  },
  members: [
    {
      id: "member-owner",
      trip_id: "demo-trip",
      user_id: "demo-user",
      role: "owner",
      joined_at: now,
      profiles: { id: "demo-user", full_name: "Cahya", avatar_url: null },
    },
    {
      id: "member-1",
      trip_id: "demo-trip",
      user_id: "member-a",
      role: "member",
      joined_at: now,
      profiles: { id: "member-a", full_name: "Nadia", avatar_url: null },
    },
    {
      id: "member-2",
      trip_id: "demo-trip",
      user_id: "member-b",
      role: "member",
      joined_at: now,
      profiles: { id: "member-b", full_name: "Bima", avatar_url: null },
    },
  ],
  itinerary: [
    {
      id: "iti-1",
      trip_id: "demo-trip",
      title: "Tiba di Lombok dan briefing",
      item_date: "2026-07-10",
      start_time: "15:00",
      end_time: "17:00",
      location: "Sembalun",
      estimated_cost: 150000,
      notes: "Cek perlengkapan dan logistik.",
      status: "planned",
      created_by: "demo-user",
      created_at: now,
      updated_at: now,
    },
    {
      id: "iti-2",
      trip_id: "demo-trip",
      title: "Mulai pendakian",
      item_date: "2026-07-11",
      start_time: "07:00",
      end_time: null,
      location: "Gerbang Sembalun",
      estimated_cost: 0,
      notes: "Berangkat pagi agar sampai pos camp tepat waktu.",
      status: "planned",
      created_by: "demo-user",
      created_at: now,
      updated_at: now,
    },
  ],
  budgetItems: [
    {
      id: "budget-1",
      trip_id: "demo-trip",
      name: "Tiket pesawat",
      category: "Transport",
      estimated_amount: 1800000,
      notes: null,
      created_by: "demo-user",
      created_at: now,
      updated_at: now,
    },
    {
      id: "budget-2",
      trip_id: "demo-trip",
      name: "Porter dan guide",
      category: "Sewa Alat",
      estimated_amount: 1200000,
      notes: "Dibagi rata.",
      created_by: "demo-user",
      created_at: now,
      updated_at: now,
    },
    {
      id: "budget-3",
      trip_id: "demo-trip",
      name: "Food and logistics",
      category: "Food",
      estimated_amount: 650000,
      notes: null,
      created_by: "demo-user",
      created_at: now,
      updated_at: now,
    },
  ],
  expenses: [
    {
      id: "expense-1",
      trip_id: "demo-trip",
      name: "DP guide",
      category: "Sewa Alat",
      amount: 900000,
      paid_by: "demo-user",
      expense_date: "2026-06-20",
      notes: null,
      split_method: "equal",
      created_by: "demo-user",
      created_at: now,
      updated_at: now,
    },
    {
      id: "expense-2",
      trip_id: "demo-trip",
      name: "Logistik awal",
      category: "Food",
      amount: 420000,
      paid_by: "member-a",
      expense_date: "2026-06-25",
      notes: "Snack dan air.",
      split_method: "equal",
      created_by: "member-a",
      created_at: now,
      updated_at: now,
    },
  ],
  expenseSplits: [],
  review: null,
};

export const demoTrips = [demoWorkspace.trip];
